name: "Jesse Allen: Lazy Engineer"
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
sass:
  sass_dir: _sass
  style: compressed
logo_url: http://www.gravatar.com/avatar/055c5f84f186142804fba9393a35ca69
collections:
  services:
    output: true
  projects:
    output: true
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: service
      body_class: service
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
      body_class: project
